TYPE=VIEW
query=select `t1`.`crfFormsID` AS `crfFormsID`,`t1`.`questionnaireID` AS `questionnaireID`,`t1`.`description` AS `description`,`ontologyURI`(\'COVIDCRFRAPID\',\'tb_crfforms\',`t1`.`crfFormsID`) AS `ontologyURI` from `trab_final`.`tb_crfforms` `t1`
md5=08cd2005d8a13251d4c6c884656a4dcd
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2020-11-05 00:19:29
create-version=2
source=select `t1`.`crfFormsID` AS `crfFormsID`,`t1`.`questionnaireID` AS `questionnaireID`,`t1`.`description` AS `description`,`ontologyURI`(\'COVIDCRFRAPID\',\'tb_crfforms\',`t1`.`crfFormsID`) AS `ontologyURI` from `tb_crfforms` `t1`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_unicode_ci
view_body_utf8=select `t1`.`crfFormsID` AS `crfFormsID`,`t1`.`questionnaireID` AS `questionnaireID`,`t1`.`description` AS `description`,`ontologyURI`(\'COVIDCRFRAPID\',\'tb_crfforms\',`t1`.`crfFormsID`) AS `ontologyURI` from `trab_final`.`tb_crfforms` `t1`
mariadb-version=100411
